### ISSUE TITLE
Wrong path format on Linux

### ISSUE THREAD

**Issue by glaroc** [LANDIS-II-Foundation/Library-Metadata#6]
Hi, I'm trying to run LANDIS on Linux and there are issues with the path  structure intended for the Metadata/ folder that gets created on each run. For example, this file gets created 

'Metadata\Base Wind\Base Wind.xml'

On the folder where Landis.Console.dll is run of instead of the Base Wind.xml file getting generated in Metadata/Base Wind/. In the end, the Metadata folder stays empty. 

It seems to just be a case of using / vs \ on Linux. 

@rmscheller

**Comment by rmscheller** [comment]
Guillaume,

I have a new dll for you to test.  You'll need to copy this into the extensions\ folder for testing purposes.
https://drive.google.com/drive/folders/0B6eUM6Se6MFBYzhhOGQ1OGYtZDI3ZC00NTEzLTk0YzAtZWNkNzliNTMyZDg4?usp=sharing

Rob

**Comment by glaroc** [comment]
I copied the .dll file into /build/extensions and ran the model and get the same problem.

https://i.imgur.com/1wb3eov.png

**Comment by rmscheller** [comment]
Does it need to be recompiled specifically for Linux?

**Comment by glaroc** [comment]
The other library files included in the support libraries seem to work fine. I tried compiling the metadata library from this repo and used it instead of the one provided with the support libraries, but the problem was still there.

**Comment by rmscheller** [comment]
Guillaume,

Of course, I didn't commit my changes and so you recompiling wouldn't work for you!   I just pushed now to a new branch:  https://github.com/LANDIS-II-Foundation/Library-Metadata/tree/path_combine

**Comment by glaroc** [comment]
I just noticed you edited your comment. The compiled library from the new branch seems to work well! Thank you!
